fix(hyperlight-component-util): emit_hl_marshal_value function to use alloc::vec instead of alloc::vec::vec
This is a fix for the issue where the emit_hl_marshal_value function was using alloc::vec::vec! instead of alloc::vec!.

The following is the build error:

```
error[E0433]: failed to resolve: could not find `vec` in `vec`
```

Signed-off-by: Jiaxiao (mossaka) Zhou <duibao55328@gmail.com>